# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.4
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [
            flake8-bugbear,
            # Handle assigment expression https://www.python.org/dev/peps/pep-0572/
            "-e",
            "git+https://github.com/pycqa/pyflakes#egg=pyflakes",
            "-e",
            "git+https://github.com/pycqa/pycodestyle#egg=pycodestyle",
          ]
        args: [--config=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: poetry run pytest -v --cov replace_with_new_name
        files: "test_*"
        verbose: true
        language: system
        types: [python]
        stages: [push, manual]
